name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Build RadiantPi.Trinnov.Altitude
      - name: Restore
        run: dotnet restore Source/RadiantPi.Trinnov.Altitude/RadiantPi.Trinnov.Altitude.csproj
      - name: Build
        run: dotnet build --no-restore --configuration Release Source/RadiantPi.Trinnov.Altitude/RadiantPi.Trinnov.Altitude.csproj
      - name: Pack
        run: dotnet pack --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o . Source/RadiantPi.Trinnov.Altitude/RadiantPi.Trinnov.Altitude.csproj

      # Build Samples
      - name: Build Show Audio Codec Sample
        run: dotnet build Samples/ShowAudioCodec/ShowAudioCodec.csproj
      - name: Build Show Audio Codec On RadiancePro Sample
        run: dotnet build Samples/ShowAudioCodecOnRadiancePro/ShowAudioCodecOnRadiancePro.csproj
      - name: Build Show Volume Sample
        run: dotnet build Samples/ShowVolume/ShowVolume.csproj

      # Publish RadiantPi.Trinnov.Altitude
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
